#!/bin/sh
git checkout master;
git fetch orig;
git rebase orig/master;
git checkout -b $(date -uI);
git am ../cip-personal-tweaks.patch;
sed -i 's/intrdocued-by/introduced-by/' issues/CVE-2024-36920.yml || true;
./scripts/import_stable.py;
sed -i 's/intrdocued-by/introduced-by/' issues/CVE-2024-36920.yml || true;
git add -A && git commit -a -m 'Import data from stable branches';
./scripts/import_debian.py;
sed -i 's/intrdocued-by/introduced-by/' issues/CVE-2024-36920.yml || true;
git add -A && git commit -a -m 'Import data from Debian';
./scripts/import_stable.py;
sed -i 's/intrdocued-by/introduced-by/' issues/CVE-2024-36920.yml || true;
git add -A && git commit -a -m 'Import data from stable branches';
./scripts/import_ubuntu.py;
sed -i 's/intrdocued-by/introduced-by/' issues/CVE-2024-36920.yml || true;
git add -A && git commit -a -m 'Import data from Ubuntu';
./scripts/import_stable.py;
sed -i 's/intrdocued-by/introduced-by/' issues/CVE-2024-36920.yml || true;
git add -A && git commit -a -m 'Import data from stable branches';
